services:
  - type: web
    name: n8n
    plan: free     # ⚡ Quan trọng: chọn Free Tier
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "123456"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "n8n.onrender.com"
      - key: WEBHOOK_URL
        value: "https://n8n.onrender.com/"
      - key: GENERIC_TIMEZONE
        value: "Asia/Ho_Chi_Minh"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: DB_SQLITE_POOL_SIZE
        value: "2"
    autoDeploy: true
